name: ldm
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - numpy
  - pandas
  - xarray
  - netcdf4
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - scikit-learn
  - absl-py
  - matplotlib
  - pyyaml
  - pip

  - pip:
      - fire
      - omegaconf
      - pytorch-lightning
